/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

import controlador.ControladorBus;
import controlador.ControladorUsuario;
import controlador.ControladorViaje;
import modelo.AdministradorFlota;
import modelo.Empresa;

/**
 *
 * @author Juan Esteban
 */
public class VentanaOpcionesAdminFlota extends javax.swing.JFrame {

    private final AdministradorFlota administradorFlota;
    private final Empresa empresa;

    public VentanaOpcionesAdminFlota(Empresa empresa, AdministradorFlota administradorFlota) {
        initComponents();
        setLocationRelativeTo(this);
        this.administradorFlota = administradorFlota;
        this.empresa = empresa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGestionarBuses = new javax.swing.JButton();
        btnGestionarViajes = new javax.swing.JButton();
        btnVenderTiquete = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnCancelarTiquete = new javax.swing.JButton();
        btnHistorialDevolucion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu Opciones"));

        btnGestionarBuses.setText("Gestionar Buses");
        btnGestionarBuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarBusesActionPerformed(evt);
            }
        });

        btnGestionarViajes.setText("Gestionar Viajes");
        btnGestionarViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarViajesActionPerformed(evt);
            }
        });

        btnVenderTiquete.setText("Vender Tiquetes");

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnCancelarTiquete.setText("Cancelar tiquete");
        btnCancelarTiquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTiqueteActionPerformed(evt);
            }
        });

        btnHistorialDevolucion.setText("Historial devoluciones");
        btnHistorialDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialDevolucionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVenderTiquete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionarViajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarTiquete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHistorialDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionarBuses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnGestionarBuses)
                .addGap(18, 18, 18)
                .addComponent(btnGestionarViajes)
                .addGap(18, 18, 18)
                .addComponent(btnVenderTiquete)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarTiquete)
                .addGap(18, 18, 18)
                .addComponent(btnHistorialDevolucion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        VentanaLogin login = new VentanaLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnGestionarBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarBusesActionPerformed
        VentanaGestionarBuses ventanaGB = new VentanaGestionarBuses(empresa);
        ventanaGB.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionarBusesActionPerformed

    private void btnGestionarViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarViajesActionPerformed
        VentanaGestionarViajes ventanaGV = new VentanaGestionarViajes(administradorFlota);
        ventanaGV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionarViajesActionPerformed

    private void btnCancelarTiqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTiqueteActionPerformed
        VentanaCancelarTiquete ventanaCT = new VentanaCancelarTiquete();
        ventanaCT.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarTiqueteActionPerformed

    private void btnHistorialDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialDevolucionActionPerformed
        VentanaHistorialDevoluciones ventanaHD = new VentanaHistorialDevoluciones();
        ventanaHD.setVisible(true);
        this.dispose();    }//GEN-LAST:event_btnHistorialDevolucionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarTiquete;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGestionarBuses;
    private javax.swing.JButton btnGestionarViajes;
    private javax.swing.JButton btnHistorialDevolucion;
    private javax.swing.JButton btnVenderTiquete;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
